version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql10
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
  
  drupal:
    image: drupal:10.1.3-fpm
    container_name: drupal10
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - drupal-data:/var/www/html
      - ./drupal/drupal-modules:/var/www/html/modules
      - ./drupal/drupal-profiles:/var/www/html/profiles
      - ./drupal/drupal-sites:/var/www/html/sites
      - ./drupal/drupal-themes:/var/www/html/themes
  
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver10
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
 
volumes:
  db-data:
  drupal-data:
