version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
  
  drupal:
    image: drupal:8.7.8-fpm
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - drupal-data:/var/www/html
      - ./drupal/drupal-modules:/var/www/html/modules
      - ./drupal/drupal-profiles:/var/www/html/profiles
      - ./drupal/drupal-sites:/var/www/html/sites
      - ./drupal/drupal-themes:/var/www/html/themes
  
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./drupal:/var/www/html/
      - ./nginx-conf:/etc/nginx/conf.d
 
volumes:
  db-data:
  drupal-data:
